
CREATE SCHEMA W1D1Assignment1
GO

/*******************************************************************************
   Create Tables
********************************************************************************/

CREATE TABLE Customers (
    CustomerId INT NOT NULL IDENTITY UNIQUE,
    FirstName NVARCHAR(40) NOT NULL,
    LastName NVARCHAR(20) NOT NULL,
    CardNumber NUMERIC(16, 0),
    CONSTRAINT PK_Customers PRIMARY KEY (CustomerId)
)

CREATE TABLE Products (
    ProductId INT NOT NULL IDENTITY UNIQUE,
    Name NVARCHAR(200) NOT NULL,
    Price NUMERIC(10, 2) NOT NULL,
    CONSTRAINT PK_Products PRIMARY KEY (ProductId)
)

CREATE TABLE Orders (
    OrderId INT NOT NULL IDENTITY UNIQUE,
    ProductId INT NOT NULL,
    CustomerId INT NOT NULL,
    CONSTRAINT PK_Orders PRIMARY KEY (OrderId),
    CONSTRAINT FK_Orders_Products FOREIGN KEY (ProductId) REFERENCES [dbo].Products,
    CONSTRAINT FK_Orders_Customers FOREIGN KEY (CustomerId) REFERENCES [dbo].Customers
)

/*******************************************************************************
   Populate Tables
********************************************************************************/

-- add at least 3 records into each table.

INSERT INTO W1D1Assignment1.Customers (FirstName, LastName, CardNumber) VALUES
    ('Lauren', 'Lister', 1111111111111111),
    ('Kaiser', 'Avalos', 2222222222222222),
    ('Rianne', 'Fry', 3333333333333333);

INSERT INTO W1D1Assignment1.Products (Name, Price) VALUES
    ('Milk, 1 Gallon', 3.49),
    ('Sandwich Bread, Loaf, Sliced', 1.99),
    ('Eggs, 1 Dozen', 3.99);

INSERT INTO W1D1Assignment1.Orders (ProductId, CustomerId) VALUES
    (1, 1),
    (2, 2),
    (3, 3);



-- add product "IPhone" priced at $200.

INSERT INTO W1D1Assignment1.Products (Name, Price) VALUES
    ('iPhone', 200.00);



-- add customer "Tina Smith".

INSERT INTO W1D1Assignment1.Customers (FirstName, LastName, CardNumber) VALUES
    ('Tina', 'Smith', 4444444444444444);



-- create order for "Tina Smith bought an iPhone".

DECLARE @tinaid INT;
SELECT @tinaid = CustomerId 
    FROM W1D1Assignment1.Customers AS c 
    WHERE c.FirstName + ' ' + c.LastName = 'Tina Smith';
DECLARE @iphoneid INT;
SELECT @iphoneid = ProductId
    FROM W1D1Assignment1.Products AS p
    WHERE p.Name = 'iPhone';
INSERT INTO W1D1Assignment1.Orders (ProductId, CustomerId) VALUES
    (@tinaid, @iphoneid);



-- report all orders by "Tina Smith".

SELECT W1D1Assignment1.Orders.*
    FROM W1D1Assignment1.Orders AS o
    LEFT JOIN W1D1Assignment1.Customers AS c ON o.CustomerId = c.CustomerId
    WHERE c.FirstName + ' ' + c.LastName = 'Tina Smith';



-- report all revenue generated by sales of 'iPhone'.

SELECT SUM(*)
    FROM W1D1Assignment1.Products



-- increase the price of 'iPhone' to $250.
UPDATE Product
SET Price = 250.00
WHERE Name = 'iPhone';
